language: python
python:
    - "2.6"
    - "2.7"
install: pip install scrapelib pymongo nose celery  --use-mirrors
script: nosetests
services: mongodb
notifications:
    email:
        - jturk@sunlightfoundation.com
