# mongodb
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DATABASE = 'oyster'
MONGO_LOG_MAXSIZE = 100000000

# scrapelib
USER_AGENT = 'oyster'
REQUESTS_PER_MINUTE = 300
REQUEST_TIMEOUT = 0
RETRY_ATTEMPTS = 0
RETRY_WAIT_SECONDS = 5
